# Generated by Django 5.1.2 on 2024-12-03 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_profile'),
        ('restaurant_app', '0004_alter_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='restaurant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.restaurant'),
        ),
    ]
