# Generated by Django 5.1.2 on 2024-12-04 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_restaurantprofile_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('cuisine_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('business_license', models.FileField(upload_to='restaurant_docs/')),
                ('food_license', models.FileField(upload_to='restaurant_docs/')),
                ('owner_id_proof', models.FileField(upload_to='restaurant_docs/')),
                ('gstin_number', models.CharField(max_length=15)),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('delivery_radius', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
