# Generated by Django 5.1.2 on 2024-12-06 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_delete_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantprofile',
            name='restaurant_banner',
            field=models.ImageField(default='default_banner.jpg', upload_to='restaurant_banners/'),
        ),
        migrations.AddField(
            model_name='restaurantprofile',
            name='restaurant_image',
            field=models.ImageField(default='default_restaurant.jpg', upload_to='restaurant_images/'),
        ),
    ]
