# Generated by Django 5.1.2 on 2024-12-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_restaurantprofile_restaurant_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantprofile',
            name='restaurant_banner',
            field=models.ImageField(default='defaults/default_banner.jpg', upload_to='restaurant_banners/'),
        ),
        migrations.AlterField(
            model_name='restaurantprofile',
            name='restaurant_image',
            field=models.ImageField(default='defaults/default_restaurant.jpg', upload_to='restaurant_images/'),
        ),
    ]
