# Generated by Django 5.1.2 on 2024-12-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_restaurant_alter_menuitem_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='default_restaurant.jpg', upload_to='restaurant_images/'),
        ),
    ]
