# Generated by Django 5.1.2 on 2024-12-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0007_alter_menuitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='category',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine_types',
        ),
        migrations.DeleteModel(
            name='RestaurantCategory',
        ),
    ]
