# Generated by Django 5.1.2 on 2024-12-06 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0009_remove_menuitem_category_menuitem_main_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='defaults/default_restaurant.jpg', upload_to='restaurant_images/'),
        ),
    ]
