# Generated by Django 5.1.2 on 2024-12-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0010_alter_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='banner',
            field=models.ImageField(default='defaults/default_banner.jpg', upload_to='restaurant_banners/'),
        ),
    ]
